import { PageHeader } from "@/components/dashboard/PageHeader";
import { StatCard } from "@/components/dashboard/StatCard";
import { stats, transactions } from "@/lib/mock-dashboard";
import { createFileRoute } from "@tanstack/react-router";
import { Sparkles } from "lucide-react";

export const Route = createFileRoute("/_app/rewards")({
    head: () => ({ meta: [{ title: "Rewards — DefiSphere" }] }),
    component: RewardsPage,
});

function RewardsPage() {
    const claims = transactions.filter((t) => t.type === "Reward Claim");
    return (
        <div className="space-y-6">
            <PageHeader
                title="Rewards"
                subtitle="Track and claim rewards generated by your staking activity."
                actions={
                    <button
                        className="inline-flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-primary-foreground"
                        style={{ background: "var(--gradient-primary)", boxShadow: "var(--shadow-glow-cyan)" }}
                    >
                        <Sparkles className="h-4 w-4" /> Claim {stats.withdrawable.toLocaleString()} USDT
                    </button>
                }
            />

            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                <StatCard label="Withdrawable" value={stats.withdrawable} icon={Sparkles} tone="cyan" />
                <StatCard index={1} label="Pending" value={stats.pending} icon={Sparkles} tone="purple" />
                <StatCard index={2} label="Lifetime Earned" value={stats.total} icon={Sparkles} tone="pink" />
            </div>

            <div className="rounded-2xl glass-card p-6">
                <h3 className="font-display text-lg font-semibold">Reward History</h3>
                <ul className="mt-4 divide-y divide-white/5">
                    {(claims.length ? claims : transactions.slice(0, 4)).map((t) => (
                        <li key={t.id} className="flex items-center justify-between py-3">
                            <div>
                                <p className="text-sm font-medium">Reward credited</p>
                                <p className="text-[11px] text-muted-foreground">{t.date}</p>
                            </div>
                            <p className="text-sm font-semibold text-emerald-300">+{t.amount.toLocaleString()} {t.asset}</p>
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    );
}
