import { AnimatePresence, motion } from "framer-motion";
import { Plus } from "lucide-react";
import { useState } from "react";

const faqs = [
    { q: "What is DFX and how do I earn it?", a: "DFX is the native reward token of DefiSphere. You earn DFX by staking supported assets, providing liquidity to whitelisted pools, voting on governance proposals, or referring new users." },
    { q: "Is DefiSphere non-custodial?", a: "Yes. All deposits live in audited smart contracts that you alone control. The DefiSphere team never has access to user funds at any point." },
    { q: "Which chains are supported?", a: "DefiSphere currently runs on Ethereum, Arbitrum, Optimism, Base, Polygon, BNB Chain and Avalanche, with unified reward accounting across all seven." },
    { q: "How are smart contracts secured?", a: "Contracts are audited by Trail of Bits and CertiK, formally verified for core vault logic, and covered by a public bug bounty up to $250,000." },
    { q: "Are there lockups or withdrawal fees?", a: "Flexible vaults have no lockups. Locked vaults offer up to 22% APY in exchange for 30–180 day commitments. There are no withdrawal fees." },
    { q: "How does the referral program work?", a: "Each wallet generates an on-chain referral code. You earn 5% of all rewards generated by direct referrals and 1% from second-tier referrals, paid in DFX." },
];

export function Faq() {
    const [open, setOpen] = useState(0);
    return (
        <section id="faq" className="relative py-24 md:py-32">
            <div className="mx-auto max-w-3xl px-5 lg:px-8">
                <div className="text-center">
                    <div className="inline-flex rounded-full glass-card px-3 py-1 text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
                        FAQ
                    </div>
                    <h2 className="mt-4 font-display text-3xl font-bold leading-tight md:text-5xl">
                        Questions, <span className="text-gradient">answered</span>
                    </h2>
                </div>

                <div className="mt-12 space-y-3">
                    {faqs.map((f, i) => {
                        const isOpen = open === i;
                        return (
                            <motion.div
                                key={f.q}
                                initial={{ opacity: 0, y: 12 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{ delay: i * 0.04 }}
                                className="overflow-hidden rounded-2xl glass-card"
                            >
                                <button
                                    onClick={() => setOpen(isOpen ? -1 : i)}
                                    className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left"
                                >
                                    <span className="font-medium">{f.q}</span>
                                    <span
                                        className="grid h-8 w-8 flex-shrink-0 place-items-center rounded-full border border-white/10 bg-white/5 transition-transform"
                                        style={{ transform: isOpen ? "rotate(45deg)" : "rotate(0)" }}
                                    >
                                        <Plus className="h-4 w-4" />
                                    </span>
                                </button>
                                <AnimatePresence initial={false}>
                                    {isOpen && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: "auto", opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.25 }}
                                        >
                                            <div className="px-5 pb-5 text-sm leading-relaxed text-muted-foreground">
                                                {f.a}
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>
                        );
                    })}
                </div>
            </div>
        </section>
    );
}