/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWithdrawRouteImport } from './routes/_app.withdraw'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppStakingRouteImport } from './routes/_app.staking'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppRewardsRouteImport } from './routes/_app.rewards'
import { Route as AppReferralsRouteImport } from './routes/_app.referrals'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDepositRouteImport } from './routes/_app.deposit'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminTransactionsRouteImport } from './routes/_admin.admin.transactions'
import { Route as AdminAdminStakingRouteImport } from './routes/_admin.admin.staking'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppStakingRoute = AppStakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTransactionsRoute = AdminAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminStakingRoute = AdminAdminStakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/deposit': typeof AppDepositRoute
  '/profile': typeof AppProfileRoute
  '/referrals': typeof AppReferralsRoute
  '/rewards': typeof AppRewardsRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/staking': typeof AppStakingRoute
  '/transactions': typeof AppTransactionsRoute
  '/wallet': typeof AppWalletRoute
  '/withdraw': typeof AppWithdrawRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/staking': typeof AdminAdminStakingRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/admin/users': typeof AdminAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/deposit': typeof AppDepositRoute
  '/profile': typeof AppProfileRoute
  '/referrals': typeof AppReferralsRoute
  '/rewards': typeof AppRewardsRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/staking': typeof AppStakingRoute
  '/transactions': typeof AppTransactionsRoute
  '/wallet': typeof AppWalletRoute
  '/withdraw': typeof AppWithdrawRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/staking': typeof AdminAdminStakingRoute
  '/admin/transactions': typeof AdminAdminTransactionsRoute
  '/admin/users': typeof AdminAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deposit': typeof AppDepositRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staking': typeof AppStakingRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/withdraw': typeof AppWithdrawRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/staking': typeof AdminAdminStakingRoute
  '/_admin/admin/transactions': typeof AdminAdminTransactionsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/deposit'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/security'
    | '/settings'
    | '/staking'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/admin/settings'
    | '/admin/staking'
    | '/admin/transactions'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/deposit'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/security'
    | '/settings'
    | '/staking'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/admin/settings'
    | '/admin/staking'
    | '/admin/transactions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/login'
    | '/_admin/admin'
    | '/_app/dashboard'
    | '/_app/deposit'
    | '/_app/profile'
    | '/_app/referrals'
    | '/_app/rewards'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/staking'
    | '/_app/transactions'
    | '/_app/wallet'
    | '/_app/withdraw'
    | '/_admin/admin/settings'
    | '/_admin/admin/staking'
    | '/_admin/admin/transactions'
    | '/_admin/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/withdraw': {
      id: '/_app/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staking': {
      id: '/_app/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof AppStakingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit': {
      id: '/_app/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/transactions': {
      id: '/_admin/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminAdminTransactionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/staking': {
      id: '/_admin/admin/staking'
      path: '/staking'
      fullPath: '/admin/staking'
      preLoaderRoute: typeof AdminAdminStakingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminStakingRoute: typeof AdminAdminStakingRoute
  AdminAdminTransactionsRoute: typeof AdminAdminTransactionsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminStakingRoute: AdminAdminStakingRoute,
  AdminAdminTransactionsRoute: AdminAdminTransactionsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepositRoute: typeof AppDepositRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStakingRoute: typeof AppStakingRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDepositRoute: AppDepositRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStakingRoute: AppStakingRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWalletRoute: AppWalletRoute,
  AppWithdrawRoute: AppWithdrawRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
